---

- name: "installing httpd"
  yum:
    name: httpd
    state: installed

- name: "starting httpd"
  service:
    name: httpd
    state: started

- name: "disbaling iptables"
  shell: service iptables stop  
  
- name: "create simple webpage and copy to html"
  shell: touch /var/www/html/index.html; echo "<strong> hello world <strong>" >> /var/www/html/index.html
